import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import cssModulesPlugin from "esbuild-css-modules-plugin";
import stylePlugin from "esbuild-style-plugin";
import fs from "fs";

const renameCssPlugin = {
  name: "rename-css",
  setup(build) {
    build.onEnd(() => {
      if (fs.existsSync("main.css")) {
        try {
          fs.copyFileSync("main.css", "styles.css");
        } catch (e) {
          console.error("CSS rename error:", e);
        }
      }
    });
  },
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,

	plugins: [
		cssModulesPlugin({
			inject: false,
		}),
		stylePlugin({
			extract: true,
		}),
		renameCssPlugin
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
